const router = require('express').Router();
const { authenticate, isAdmin } = require('../middleware/auth');
const { register, login, verifyToken, getProfile, getAllUsers, deleteUser, requestRegisterOtp, verifyRegisterOtp, changePhone, changePassword, syncName, toggleUserStatus } = require('../controllers/authController');
router.put('/change-phone', authenticate, changePhone);
router.put('/change-password', authenticate, changePassword);
router.put('/internal/:userId/sync-name', syncName);
router.put('/users/:id/status', authenticate, isAdmin, toggleUserStatus);
router.post('/register', register);
router.post('/register/request-otp', requestRegisterOtp);
router.post('/register/verify-otp', verifyRegisterOtp);
router.post('/login', login);
router.get('/verify', authenticate, verifyToken);
router.get('/profile', authenticate, getProfile);
router.get('/users', authenticate, isAdmin, getAllUsers);
router.delete('/users/:id', authenticate, isAdmin, deleteUser);
module.exports = router;
