const express = require('express');
const cors = require('cors');
require('dotenv').config();
const app = express();
const path = require('path');
app.use(cors());
app.use(express.json({ limit: '5mb' }));
app.use('/uploads', express.static(path.join(__dirname, '../uploads')));app.use('/api', require('./routes/productRoutes'));
app.get('/health', (_, res) => res.json({ service: 'product-service', status: 'ok' }));
app.listen(process.env.PORT || 5003, () => console.log(`Product Service :${process.env.PORT || 5003}`));
